# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install
        npm i -D @playwright/test
        npx playwright install
        npm i -D @applitools/eyes-playwright
    - run: |
        PLAYWRIGHT_JUNIT_OUTPUT_NAME=results.xml 
        APPLITOOLS_API_KEY="${{ secrets.EYES_API_KEY }}" npx playwright test ./tests/* browser=chromium --reporter=junit,line
        pwd
        ls -li
        sed -i '' -e 's/<system-out>/<properties><property name="testrun_comment"><![CDATA[/g' ./tests/results.xml
        sed -i '' -e 's/<\/system-out>/]]><\/property><\/properties>/g' ./tests/results.xml
    - name: "Import results to Xray (cloud)"
      uses: mikepenz/xray-action@v2.0.0
      with:
         username: "${{ secrets.XRAYCLOUD_CLIENT_ID }}"
         password: "${{ secrets.XRAYCLOUD_CLIENT_SECRET }}"
         xrayCloud: "true"
         testFormat: "junit"
         testPaths: "**/tests/*.xml"
         testPlanKey: "${{ secrets.XRAYCLOUD_TEST_PLAN_KEY }}"
         projectKey: "${{ secrets.JIRACLOUD_PROJECT_KEY }}"    
    
